// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqEV4vvMKTm-649MhbwmQ8Tul8wINjAw',
    appId: '1:609290298225:web:40b0481393a5028139ccd0',
    messagingSenderId: '609290298225',
    projectId: 'wallpaper-549f3',
    authDomain: 'wallpaper-549f3.firebaseapp.com',
    storageBucket: 'wallpaper-549f3.appspot.com',
    measurementId: 'G-0X42EZ57NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGE3blb7kaLKS9EsFMWWkyjC4kVJD8EBU',
    appId: '1:609290298225:android:5ee380021f9c08da39ccd0',
    messagingSenderId: '609290298225',
    projectId: 'wallpaper-549f3',
    storageBucket: 'wallpaper-549f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZAXAu4KgqSy4yoCUMXj4nUTBbJusSJAI',
    appId: '1:609290298225:ios:7b4bdbe6fe31c90a39ccd0',
    messagingSenderId: '609290298225',
    projectId: 'wallpaper-549f3',
    storageBucket: 'wallpaper-549f3.appspot.com',
    iosBundleId: 'com.example.wallpapertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZAXAu4KgqSy4yoCUMXj4nUTBbJusSJAI',
    appId: '1:609290298225:ios:7b4bdbe6fe31c90a39ccd0',
    messagingSenderId: '609290298225',
    projectId: 'wallpaper-549f3',
    storageBucket: 'wallpaper-549f3.appspot.com',
    iosBundleId: 'com.example.wallpapertask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqEV4vvMKTm-649MhbwmQ8Tul8wINjAw',
    appId: '1:609290298225:web:f05f3cc94167923739ccd0',
    messagingSenderId: '609290298225',
    projectId: 'wallpaper-549f3',
    authDomain: 'wallpaper-549f3.firebaseapp.com',
    storageBucket: 'wallpaper-549f3.appspot.com',
    measurementId: 'G-GVTFYTYL6H',
  );
}
